// reminder — the Node port of Mark LIV's actions/reminder.py.
//
// A reminder is handed to the OS scheduler, so it fires even when Jarvis is
// closed. Mark scheduled a small Python script; jarvis-lite has no Python, so
// the fired job is native to each OS instead:
//   Windows — a Task Scheduler task (JARVISReminder_YYYYMMDD_HHMMSS, registered
//             from XML like Mark) that runs a hidden PowerShell script: a toast,
//             falling back to `msg *` then a tray balloon, plus Mark's 3-tone beep.
//   macOS   — a LaunchAgent running a sh script that calls osascript.
//   Linux   — `systemd-run --user --on-calendar`, else `at`, running a sh script
//             that calls notify-send.
// Every script deletes itself after firing, as Mark's did.
//
// cancelReminder(taskName) (not a tool) removes a scheduled reminder again.

const fs = require('fs');
const os = require('os');
const path = require('path');
const { run } = require('../util/ps');

const TITLE = 'J.A.R.V.I.S Reminder';
const TASK_RE = /^JARVISReminder_\d{8}_\d{6}$/;
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September',
  'October', 'November', 'December'];
const pad2 = (n) => String(n).padStart(2, '0');

function getOs() {
  return { win32: 'windows', darwin: 'mac' }[process.platform] || 'linux';
}

function scriptsDir() {
  const d = path.join(os.homedir(), '.jarvis', 'reminders');
  fs.mkdirSync(d, { recursive: true });
  return d;
}

// Mark strips backslashes and quotes so the message can sit inside any quoted
// literal of the generated script; the sh scripts below rely on that.
function sanitise(text, maxLen = 200) {
  return String(text || '')
    .replace(/\\/g, '')
    .replace(/"/g, '')
    .replace(/'/g, '')
    .replace(/\n/g, ' ')
    .replace(/\r/g, '')
    .trim()
    .slice(0, maxLen);
}

const xmlEscape = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const stamp = (d) =>
  `${d.getFullYear()}${pad2(d.getMonth() + 1)}${pad2(d.getDate())}_${pad2(d.getHours())}${pad2(d.getMinutes())}${pad2(d.getSeconds())}`;

/** strptime("%Y-%m-%d %H:%M") — local time; null when malformed or impossible (Feb 30). */
function parseTarget(dateStr, timeStr) {
  const m = /^(\d{4})-(\d{1,2})-(\d{1,2}) (\d{1,2}):(\d{1,2})$/.exec(`${dateStr} ${timeStr}`);
  if (!m) return null;
  const [y, mo, d, h, mi] = m.slice(1).map(Number);
  if (h > 23 || mi > 59) return null;
  const dt = new Date(y, mo - 1, d, h, mi, 0, 0);
  if (dt.getFullYear() !== y || dt.getMonth() !== mo - 1 || dt.getDate() !== d) return null;
  return dt;
}

/** strftime("%B %d at %I:%M %p") */
function friendly(d) {
  const h12 = d.getHours() % 12 || 12;
  return `${MONTHS[d.getMonth()]} ${pad2(d.getDate())} at ${pad2(h12)}:${pad2(d.getMinutes())} ${d.getHours() < 12 ? 'AM' : 'PM'}`;
}

// ── Notify scripts ───────────────────────────────────────────────────────────

function winScript(message) {
  // The message travels base64-encoded, so no character in it can break out
  // of a PowerShell literal.
  const b64 = Buffer.from(message, 'utf8').toString('base64');
  return `# Auto-generated by J.A.R.V.I.S reminder — do not edit
$ErrorActionPreference = 'Stop'
$message = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${b64}'))
$title = '${TITLE}'
$notified = $false

try {
  [void][Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime]
  $tpl = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent([Windows.UI.Notifications.ToastTemplateType]::ToastText02)
  $texts = $tpl.GetElementsByTagName('text')
  [void]$texts.Item(0).AppendChild($tpl.CreateTextNode($title))
  [void]$texts.Item(1).AppendChild($tpl.CreateTextNode($message))
  $toast = New-Object Windows.UI.Notifications.ToastNotification $tpl
  # PowerShell's own AppUserModelID: always registered, so the toast shows
  # without Jarvis having to install a Start-menu shortcut.
  $appId = '{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\WindowsPowerShell\\v1.0\\powershell.exe'
  [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier($appId).Show($toast)
  $notified = $true
} catch { }

if (-not $notified) {
  try {
    & msg.exe '*' '/TIME:30' $message 2>$null
    if ($LASTEXITCODE -eq 0) { $notified = $true }
  } catch { }
}

if (-not $notified) {
  try {
    Add-Type -AssemblyName System.Windows.Forms, System.Drawing
    $icon = New-Object System.Windows.Forms.NotifyIcon
    $icon.Icon = [System.Drawing.SystemIcons]::Information
    $icon.Visible = $true
    $icon.ShowBalloonTip(15000, $title, $message, [System.Windows.Forms.ToolTipIcon]::Info)
    Start-Sleep -Seconds 15
    $icon.Dispose()
  } catch { }
}

try {
  foreach ($freq in 800, 1000, 1200) { [Console]::Beep($freq, 180); Start-Sleep -Milliseconds 80 }
} catch { }

# Self-delete after firing
try { Remove-Item -LiteralPath $PSCommandPath -Force } catch { }
`;
}

function shScript(message, osName, extraCleanup = '') {
  const notify =
    osName === 'mac'
      ? `osascript -e 'display notification "${message}" with title "${TITLE}"'`
      : `notify-send --urgency=normal --expire-time=15000 '${TITLE}' '${message}'`;
  return `#!/bin/sh
# Auto-generated by J.A.R.V.I.S reminder — do not edit
${notify} >/dev/null 2>&1
${extraCleanup}
# Self-delete after firing
rm -f "$0"
`;
}

function writeNotifyScript(taskName, message, osName) {
  const dir = scriptsDir();
  if (osName === 'windows') {
    const p = path.join(dir, `${taskName}.ps1`);
    // BOM so Windows PowerShell 5.1 reads the file as UTF-8, not the ANSI codepage.
    fs.writeFileSync(p, `\ufeff${winScript(message)}`, 'utf8');
    return p;
  }
  const p = path.join(dir, `${taskName}.sh`);
  // On macOS the agent's plist is removed too, so launchd never re-fires it.
  const cleanup = osName === 'mac' ? `rm -f "${macPlistPath(taskName)}"` : '';
  fs.writeFileSync(p, shScript(message, osName, cleanup), { encoding: 'utf8', mode: 0o600 });
  try {
    fs.chmodSync(p, 0o600); // owner read/write only
  } catch {
    /* ignore */
  }
  return p;
}

const rmQuiet = (p) => {
  try {
    fs.rmSync(p, { force: true });
  } catch {
    /* ignore */
  }
};

// ── Schedulers ───────────────────────────────────────────────────────────────

async function scheduleWindows(target, taskName, scriptPath) {
  const ps = path.join(process.env.SystemRoot || 'C:\\Windows', 'System32', 'WindowsPowerShell', 'v1.0', 'powershell.exe');
  const args = `-NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File "${scriptPath}"`;
  const start = `${target.getFullYear()}-${pad2(target.getMonth() + 1)}-${pad2(target.getDate())}T${pad2(target.getHours())}:${pad2(target.getMinutes())}:${pad2(target.getSeconds())}`;

  const xmlPath = path.join(scriptsDir(), `${taskName}.xml`);
  const xml =
    '<?xml version="1.0" encoding="UTF-16"?>\n' +
    '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\n' +
    `  <RegistrationInfo><Description>${TITLE}</Description></RegistrationInfo>\n` +
    '  <Triggers><TimeTrigger>\n' +
    `    <StartBoundary>${start}</StartBoundary>\n` +
    '    <Enabled>true</Enabled>\n' +
    '  </TimeTrigger></Triggers>\n' +
    '  <Actions><Exec>\n' +
    `    <Command>${xmlEscape(ps)}</Command>\n` +
    `    <Arguments>${xmlEscape(args)}</Arguments>\n` +
    '  </Exec></Actions>\n' +
    '  <Settings>\n' +
    '    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n' +
    '    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n' +
    '    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n' +
    '    <StartWhenAvailable>true</StartWhenAvailable>\n' +
    '    <ExecutionTimeLimit>PT5M</ExecutionTimeLimit>\n' +
    '    <Enabled>true</Enabled>\n' +
    '  </Settings>\n' +
    '  <Principals><Principal>\n' +
    '    <LogonType>InteractiveToken</LogonType>\n' +
    '    <RunLevel>LeastPrivilege</RunLevel>\n' +
    '  </Principal></Principals>\n' +
    '</Task>';
  // schtasks wants the encoding the declaration names: UTF-16 LE with a BOM.
  fs.writeFileSync(xmlPath, Buffer.from(`\ufeff${xml}`, 'utf16le'));

  const r = await run('schtasks.exe', ['/Create', '/TN', taskName, '/XML', xmlPath, '/F'], { timeout: 20_000 });
  rmQuiet(xmlPath);

  if (!r.ok) {
    rmQuiet(scriptPath);
    console.log(`[Reminder] ❌ schtasks: ${(r.stderr || r.stdout).trim()}`);
    return '';
  }
  return taskName;
}

function macPlistPath(taskName) {
  return path.join(os.homedir(), 'Library', 'LaunchAgents', `com.jarvis.reminder.${taskName}.plist`);
}

async function scheduleMac(target, taskName, scriptPath) {
  const plistPath = macPlistPath(taskName);
  fs.mkdirSync(path.dirname(plistPath), { recursive: true });
  const label = `com.jarvis.reminder.${taskName}`;

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>             <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${xmlEscape(scriptPath)}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Year</key>   <integer>${target.getFullYear()}</integer>
    <key>Month</key>  <integer>${target.getMonth() + 1}</integer>
    <key>Day</key>    <integer>${target.getDate()}</integer>
    <key>Hour</key>   <integer>${target.getHours()}</integer>
    <key>Minute</key> <integer>${target.getMinutes()}</integer>
  </dict>
  <key>RunAtLoad</key>         <false/>
  <key>StandardOutPath</key>   <string>/dev/null</string>
  <key>StandardErrorPath</key> <string>/dev/null</string>
</dict>
</plist>
`;
  fs.writeFileSync(plistPath, plist, { encoding: 'utf8', mode: 0o644 });

  const r = await run('launchctl', ['load', plistPath], { timeout: 15_000 });
  if (!r.ok) {
    rmQuiet(plistPath);
    rmQuiet(scriptPath);
    console.log(`[Reminder] ❌ launchctl: ${r.stderr.trim()}`);
    return '';
  }
  return label;
}

async function scheduleLinux(target, taskName, scriptPath) {
  const onCalendar = `${target.getFullYear()}-${pad2(target.getMonth() + 1)}-${pad2(target.getDate())} ${pad2(target.getHours())}:${pad2(target.getMinutes())}:00`;
  const sd = await run('systemd-run', ['--user', `--on-calendar=${onCalendar}`, `--unit=${taskName}`, '--', '/bin/sh', scriptPath], { timeout: 15_000 });
  if (sd.ok) return taskName;
  if (!/ENOENT/.test(sd.stderr)) console.log(`[Reminder] ⚠️ systemd-run failed: ${sd.stderr.trim()}, trying 'at'`);

  const atTime = `${pad2(target.getHours())}:${pad2(target.getMinutes())} ${target.getFullYear()}-${pad2(target.getMonth() + 1)}-${pad2(target.getDate())}`;
  const at = await run('at', [atTime], { timeout: 15_000, input: `/bin/sh '${scriptPath.replace(/'/g, "'\\''")}'\n` });
  if (at.ok) {
    // Remember the job number so cancelReminder can atrm it.
    const job = /job\s+(\d+)/.exec(at.stderr + at.stdout);
    if (job) fs.writeFileSync(path.join(scriptsDir(), `${taskName}.atjob`), job[1], 'utf8');
    return taskName;
  }
  if (/ENOENT/.test(at.stderr) && /ENOENT/.test(sd.stderr)) {
    console.log('[Reminder] ❌ Neither systemd-run nor at found on this Linux system.');
  } else {
    console.log(`[Reminder] ❌ at: ${at.stderr.trim()}`);
  }
  return '';
}

// ── Tool ─────────────────────────────────────────────────────────────────────

async function reminder(parameters, ctx) {
  const p = parameters || {};
  const dateStr = String(p.date || '').trim();
  const timeStr = String(p.time || '').trim();
  const message = String(p.message || 'Reminder').trim();

  if (!dateStr || !timeStr) return 'I need both a date and a time to set a reminder.';

  const target = parseTarget(dateStr, timeStr);
  if (!target) return "I couldn't parse that date or time. Please use YYYY-MM-DD and HH:MM.";
  if (target.getTime() <= Date.now()) return "That time has already passed — I can't set a reminder in the past.";

  const osName = getOs();
  const safeMsg = sanitise(message);
  const taskName = `JARVISReminder_${stamp(target)}`;

  let scriptPath;
  try {
    scriptPath = writeNotifyScript(taskName, safeMsg, osName);
  } catch (e) {
    return `Could not prepare the reminder script: ${e.message || e}`;
  }

  let jobId = '';
  try {
    if (osName === 'windows') jobId = await scheduleWindows(target, taskName, scriptPath);
    else if (osName === 'mac') jobId = await scheduleMac(target, taskName, scriptPath);
    else jobId = await scheduleLinux(target, taskName, scriptPath);
  } catch (e) {
    rmQuiet(scriptPath);
    console.log(`[Reminder] ❌ Scheduling exception: ${e.message || e}`);
    return 'Something went wrong while scheduling the reminder.';
  }

  if (!jobId) return "I couldn't register the reminder with the system scheduler.";

  ctx?.ui?.log?.(`[Reminder] ✅ ${dateStr} ${timeStr} — ${safeMsg.slice(0, 40)}`);
  return `Reminder set for ${friendly(target)}.`;
}

/**
 * Remove a reminder scheduled by this module (not a tool). `taskName` is the
 * JARVISReminder_YYYYMMDD_HHMMSS name (see taskNameFor). Resolves
 * { ok, detail } and never rejects.
 */
async function cancelReminder(taskName) {
  taskName = String(taskName || '').trim();
  if (!TASK_RE.test(taskName)) return { ok: false, detail: `Not a reminder task name: '${taskName}'.` };
  const dir = path.join(os.homedir(), '.jarvis', 'reminders');
  const osName = getOs();
  let ok = false;
  let detail = '';

  if (osName === 'windows') {
    const r = await run('schtasks.exe', ['/Delete', '/TN', taskName, '/F'], { timeout: 15_000 });
    ok = r.ok;
    detail = ok ? `Reminder ${taskName} cancelled.` : `No such reminder: ${(r.stderr || r.stdout).trim()}`;
    rmQuiet(path.join(dir, `${taskName}.ps1`));
  } else if (osName === 'mac') {
    const plistPath = macPlistPath(taskName);
    if (fs.existsSync(plistPath)) {
      await run('launchctl', ['unload', plistPath], { timeout: 15_000 });
      rmQuiet(plistPath);
      ok = true;
    }
    detail = ok ? `Reminder ${taskName} cancelled.` : 'No such reminder.';
    rmQuiet(path.join(dir, `${taskName}.sh`));
  } else {
    const sd = await run('systemctl', ['--user', 'stop', `${taskName}.timer`], { timeout: 15_000 });
    ok = sd.ok;
    const jobFile = path.join(dir, `${taskName}.atjob`);
    if (fs.existsSync(jobFile)) {
      const job = fs.readFileSync(jobFile, 'utf8').trim();
      if (/^\d+$/.test(job) && (await run('atrm', [job], { timeout: 15_000 })).ok) ok = true;
      rmQuiet(jobFile);
    }
    detail = ok ? `Reminder ${taskName} cancelled.` : 'No such reminder.';
    rmQuiet(path.join(dir, `${taskName}.sh`));
  }
  return { ok, detail };
}

/** The scheduler task name the tool uses for a given date/time, or '' if unparsable. */
function taskNameFor(date, time) {
  const t = parseTarget(String(date || '').trim(), String(time || '').trim());
  return t ? `JARVISReminder_${stamp(t)}` : '';
}

module.exports = {
  TOOL: {
    name: 'reminder',
    description: 'Sets a timed reminder using Task Scheduler.',
    parameters: {
      type: 'OBJECT',
      properties: {
        date: { type: 'STRING', description: 'Date in YYYY-MM-DD format' },
        time: { type: 'STRING', description: 'Time in HH:MM format (24h)' },
        message: { type: 'STRING', description: 'Reminder message text' },
      },
      required: ['date', 'time', 'message'],
    },
  },
  run: reminder,
  cancelReminder,
  taskNameFor,
};
